//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.HospitalDeliveries = new HashSet<HospitalDelivery>();
        }
    
        public int DeliveryID { get; set; }
        public long ReportingQuarterID { get; set; }
        public string CqsSource { get; set; }
        public string VbpSource { get; set; }
        public string UtilizationSource { get; set; }
        public Nullable<long> CqsReportingQuarterIDBegin { get; set; }
        public Nullable<long> CqsReportingQuarterIDEnd { get; set; }
        public Nullable<long> VpbReportingQuarterIDBegin { get; set; }
        public Nullable<long> VbpReportingQuarterIDEnd { get; set; }
        public Nullable<long> UtilizationReportingQuarterIDBegin { get; set; }
        public Nullable<long> UtilizationReportingQuarterIDEnd { get; set; }
        public string Domain1Name { get; set; }
        public string Domain2Name { get; set; }
        public string Domain3Name { get; set; }
        public string Domain4Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalDelivery> HospitalDeliveries { get; set; }
    }
}
