//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HospitalDelivery()
        {
            this.Utilizations = new HashSet<Utilization>();
        }
    
        public int DeliveryID { get; set; }
        public string CCN { get; set; }
        public long HospitalID { get; set; }
        public string HospitalName { get; set; }
        public string HospitalCity { get; set; }
        public string HospitalState { get; set; }
        public Nullable<decimal> CqsNationalPercentile { get; set; }
        public Nullable<byte> CqsNationalRatingID { get; set; }
        public Nullable<decimal> RamiNationalPercentile { get; set; }
        public Nullable<byte> RamiNationalRatingID { get; set; }
        public Nullable<decimal> RaciNationalPercentile { get; set; }
        public Nullable<byte> RaciNationalRatingID { get; set; }
        public Nullable<decimal> RariNationalPercentile { get; set; }
        public Nullable<byte> RariNationalRatingID { get; set; }
        public Nullable<decimal> PsiNationalPercentile { get; set; }
        public Nullable<byte> PsiNationalRatingID { get; set; }
        public Nullable<decimal> IqiNationalPercentile { get; set; }
        public Nullable<byte> IqiNationalRatingID { get; set; }
        public Nullable<decimal> VbpDomain1Score { get; set; }
        public Nullable<decimal> VbpDomain2Score { get; set; }
        public Nullable<decimal> VbpDomain3Score { get; set; }
        public Nullable<decimal> VbpDomain4Score { get; set; }
        public Nullable<decimal> VbpTotalPerformanceScore { get; set; }
        public Nullable<decimal> VbpDomain1Percentile { get; set; }
        public Nullable<decimal> VbpDomain2Percentile { get; set; }
        public Nullable<decimal> VbpDomain3Percentile { get; set; }
        public Nullable<decimal> VbpDomain4Percentile { get; set; }
        public Nullable<decimal> VbpTotalPerformancePercentile { get; set; }
        public Nullable<byte> VbpDomain1RatingID { get; set; }
        public Nullable<byte> VbpDomain2RatingID { get; set; }
        public Nullable<byte> VbpDomain3RatingID { get; set; }
        public Nullable<byte> VbpDomain4RatingID { get; set; }
        public Nullable<byte> VbpTotalPerformanceRatingID { get; set; }
        public Nullable<decimal> VbpIncentivePaymentPercentage { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilization> Utilizations { get; set; }
    }
}
