//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilization
    {
        public int DeliveryID { get; set; }
        public long HospitalID { get; set; }
        public long ReportingQuarterID { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<decimal> ActualLos { get; set; }
        public Nullable<decimal> ComparitiveCost { get; set; }
        public Nullable<decimal> ComparitiveLos { get; set; }
        public Nullable<byte> CostRatingID { get; set; }
        public Nullable<byte> LosRatingID { get; set; }
    
        public virtual HospitalDelivery HospitalDelivery { get; set; }
    }
}
