//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visualization
    {
        public string CCN { get; set; }
        public long ReportingQuarterID { get; set; }
        public Nullable<System.Guid> FieldId { get; set; }
        public string BlobWebAddress { get; set; }
        public byte[] BlobPdf { get; set; }
    }
}
